### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by sfmskywalker** [bs-components/bs-components#3]
Do you have any plans on adding a Toast component (https://getbootstrap.com/docs/4.4/components/toasts/)?

If not, I'll try and work on a PR.

**Comment by bs-components** [comment]
HA!  That didn't take long to get a PR.  :-)  When I built this they didn't have toasts.

I looked over your PR and I like how you did it.  I don't see any problem accepting it as long as we don't list the toasts as being tested in the readme.  If you have interest and time right now I should probably figure out how to make you one of the maintainers.  Let me know if you are interested in that.

As far as tests go I'll have to look at that when I have time.  I seem to remember you just did the npm install and then ran `npm run test-bs-dropdown` or something to that effect.  It was all in the package.json  Maybe stencil and testcafe had to be installed globally.  It's been awhile since I ran them though, hopefully testcafe doesn't have any breaking changes.  I was basically just trying to copy all the tests that bootstrap has in their repo but using testcafe.  I'm heading out of country for a few weeks so I won't be able to chase that anytime soon.

**Comment by sfmskywalker** [comment]
It was easier than I thought :) But in all fairness, I basically took one of the existing components as a template and renamed and removed some stuff. The initial version works well, although I suspect it might need an update or two to make manipulating the component easier from other components using binding mechanisms. Or maybe not, we'll see. I'm about to use it in another project. In any case, I'd certainly be honored to become a maintainer of this project.

Regarding tests and testcafe, I figured it out. The globally installed version (1.8.1) worked, but when running the command from within my local bs-component project folder, it takes the locally installed version (^15.1.317922, which interestingly enough is *not* the latest version, despite the major version (15) being larger than 1). Looking at the Releases tab on the testcafee project, I confirmed that the latest version is indeed 1.8.1. I'll try and add a few tests.

Safe travels!
